#define PROTO_NAME "PROTO_NAME"
#define PROTO_NAME_UPPER "PROTO_NAME_UPPER"
#define PROTO_PACKAGE "PROTO_PACKAGE"
#define PROTO_NAMESPACE "PROTO_NAMESPACE"

// for package a.b PROTO_NAMEPATH is /a/b PROTO_NAMEPATH_DOT is /a.b
#define PROTO_NAMEPATH "PROTO_NAMEPATH"
#define PROTO_NAMEPATH_DOT "PROTO_NAMEPATH_DOT"

#define PROTO_SERVER_NAME "PROTO_SERVER_NAME"
#define PROTO_SERVER_NAME_LOWER "PROTO_SERVER_NAME_LOWER"


#define PROTO_SERVER_METHOD_NAME "PROTO_SERVER_METHOD_NAME"
#define PROTO_SERVER_METHOD_REQUEST_NAME "PROTO_SERVER_METHOD_REQUEST_NAME"
#define PROTO_SERVER_METHOD_RESPONSE_NAME "PROTO_SERVER_METHOD_RESPONSE_NAME"

