# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inspect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inspect.proto',
  package='ngxrpc.inspect',
  syntax='proto3',
  serialized_pb=_b('\n\rinspect.proto\x12\x0engxrpc.inspect\"\x17\n\x07Request\x12\x0c\n\x04json\x18\x01 \x01(\x0c\"\x18\n\x08Response\x12\x0c\n\x04json\x18\x01 \x01(\x0c\x32\x91\x01\n\x0b\x41pplication\x12>\n\tinterface\x12\x17.ngxrpc.inspect.Request\x1a\x18.ngxrpc.inspect.Response\x12\x42\n\rrequeststatus\x12\x17.ngxrpc.inspect.Request\x1a\x18.ngxrpc.inspect.ResponseB\x06\x80\x01\x00\xf8\x01\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='ngxrpc.inspect.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json', full_name='ngxrpc.inspect.Request.json', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=56,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='ngxrpc.inspect.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json', full_name='ngxrpc.inspect.Response.json', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'inspect_pb2'
  # @@protoc_insertion_point(class_scope:ngxrpc.inspect.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'inspect_pb2'
  # @@protoc_insertion_point(class_scope:ngxrpc.inspect.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\000\370\001\001'))
# @@protoc_insertion_point(module_scope)
